import { Routes } from '@angular/router';
import { HomeComponent } from './modules/home/home/home.component';
import { ContactComponent } from './modules/contact/contact.component';
import { BlogComponent } from './modules/blogs/blog/blog.component';
import { BenefitsApiImplementingComponent } from './modules/blogs/benefits-api-implementing/benefits-api-implementing.component';
import { JavaFutureComponent } from './modules/blogs/java-future/java-future.component';
import { ReactjsPopularComponent } from './modules/blogs/reactjs-popular/reactjs-popular.component';
import { MostPopularComponent } from './modules/blogs/most-popular/most-popular.component';
import { PortfolioComponent } from './modules/company/portfolio/portfolio.component';
import { AboutUsComponent } from './modules/company/about-us/about-us.component';
import { SoftwareProductDevelopmentComponent } from './modules/services/software-product-development/software-product-development.component';
import { CustomerSoftwareDevelopmentComponent } from './modules/services/customer-software-development/customer-software-development.component';
import { SaasDevelopmentComponent } from './modules/services/saas-development/saas-development.component';
import { ApplicationDevelopmentComponent } from './modules/services/application-development/application-development.component';
import { WebAppDevelopmentComponent } from './modules/services/web-app-development/web-app-development.component';
import { SoftwareTestingComponent } from './modules/services/software-testing/software-testing.component';
import { UiuxDesignComponent } from './modules/services/uiux-design/uiux-design.component';
import { CloudServicesComponent } from './modules/services/cloud-services/cloud-services.component';
import { AngularComponent } from './modules/technologies/frontend/angular/angular.component';
import { NextjsComponent } from './modules/technologies/frontend/nextjs/nextjs.component';
import { ReactComponent } from './modules/technologies/frontend/react/react.component';
import { DotNetComponent } from './modules/technologies/backend/dot-net/dot-net.component';
import { NodeJsComponent } from './modules/technologies/backend/node-js/node-js.component';
import { JavaComponent } from './modules/technologies/backend/java/java.component';
import { NestJsComponent } from './modules/technologies/backend/nest-js/nest-js.component';
import { IosComponent } from './modules/technologies/mobile/ios/ios.component';
import { AndroidComponent } from './modules/technologies/mobile/android/android.component';
import { ReactNativeComponent } from './modules/technologies/mobile/react-native/react-native.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'contact', component: ContactComponent },
    { path: 'blog', component: BlogComponent },
    { path: 'benifit', component: BenefitsApiImplementingComponent },
    { path: 'most-popular', component: MostPopularComponent },
    { path: 'react-popular', component: ReactjsPopularComponent },
    { path: 'java-future', component: JavaFutureComponent },
    { path: 'portfolio', component: PortfolioComponent },
    { path: 'about_us', component: AboutUsComponent },
    { path: 'softwareproduct', component: SoftwareProductDevelopmentComponent },
    { path: 'customer-software-developmen', component: CustomerSoftwareDevelopmentComponent },
    { path: 'saas-development-service', component: SaasDevelopmentComponent },
    { path: 'application-development', component: ApplicationDevelopmentComponent },
    { path: 'web-development', component: WebAppDevelopmentComponent },
    { path: 'software-testing', component: SoftwareTestingComponent },
    { path: 'uiux-design', component: UiuxDesignComponent },
    { path: 'cloud-services', component: CloudServicesComponent },
    { path: 'react', component: ReactComponent },
    { path: 'angular', component: AngularComponent },
    { path: 'next', component: NextjsComponent },
    { path: 'dot-net', component: DotNetComponent },
    { path: 'nodejs', component: NodeJsComponent },
    { path: 'java', component: JavaComponent },
    { path: 'nest', component: NestJsComponent },
    { path: 'ios', component: IosComponent },
    { path: 'android', component: AndroidComponent },
    { path: 'react-native', component: ReactNativeComponent },
    { path: '**', component: HomeComponent },
];
